version: '3'

services:
  database:
    container_name: postgres_db
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - ./config/database.env
    volumes:
      - database-data:/var/lib/postgresql/data/
    restart: always

  web-scraper:
    container_name: web_scraper_app
    build:
      context: ./web_scraper
    depends_on:
      - flask-app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./web_scraper/application/log:/home/application/log
    command: [ python, app.py ]

  flask-app:
    build:
      context: ./api
    container_name: flask_api
    depends_on:
      - database
    privileged: true
    ports:
      - 5000:5000
    volumes:
      - ./api/application/log:/home/application/log
    command: [ python, app.py ]
    restart: always

volumes:
  database-data:


